export const POST_BY_ID_SUCCESS = "POST_BY_ID_SUCCESS";
export const POST_BY_ID_FAILED = "POST_BY_ID_FAILED";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILED = "POST_FAILED";
export const POST_FAVORITE_SUCCESS = "POST_FAVORITE_SUCCESS";
export const POST_FAVORITE_FAILED = "POST_FAVORITE_FAILED";